/* 中文常见字 (common words) vol. 1 — the class flashcard deck.
   sheet = the teacher's card sheet (PDF pages 2n-1 / 2n).
   s = toneless syllables the character can be read as (used to accept homophones
   when checking speech). Meanings and "built" notes are written for kids. */
window.MANDARIN_DECKS = window.MANDARIN_DECKS || {};
window.MANDARIN_DECKS["common-words-1"] = {
  title: "中文常见字",
  cards: [
    { c: "你", py: "nǐ", s: ["ni"], en: "you", rad: "亻 person", built: "亻 person + 尔 for the sound", sheet: 1 },
    { c: "我", py: "wǒ", s: ["wo"], en: "I, me", rad: "戈 spear", built: "A hand holding a 戈 spear to protect myself", sheet: 1 },
    { c: "他", py: "tā", s: ["ta"], en: "he, him", rad: "亻 person", built: "亻 person + 也 for the sound", sheet: 1 },
    { c: "她", py: "tā", s: ["ta"], en: "she, her", rad: "女 woman", built: "女 woman + 也 for the sound", sheet: 1 },
    { c: "姐", py: "jiě", s: ["jie"], en: "big sister", rad: "女 woman", built: "女 woman + 且 for the sound", sheet: 1 },
    { c: "妹", py: "mèi", s: ["mei"], en: "little sister", rad: "女 woman", built: "女 woman + 未 for the sound", sheet: 1 },
    { c: "哥", py: "gē", s: ["ge"], en: "big brother", rad: "口 mouth", built: "可 stacked on 可 — and 可 gives the sound", sheet: 1 },
    { c: "弟", py: "dì", s: ["di"], en: "little brother", rad: "弓 bow", built: "A picture of thread wrapped around a spindle", sheet: 1 },
    { c: "家", py: "jiā", s: ["jia"], en: "home, family", rad: "宀 roof", built: "宀 roof over 豕 a pig — a home with animals", sheet: 1 },
    { c: "人", py: "rén", s: ["ren"], en: "person, people", rad: "人 person", built: "A picture of a person walking on two legs", sheet: 1 },

    { c: "朋", py: "péng", s: ["peng"], en: "friend", rad: "月 moon", built: "Two 月 side by side — like two friends walking together", sheet: 2 },
    { c: "友", py: "yǒu", s: ["you"], en: "friend", rad: "又 hand", built: "Two hands together — friendship", sheet: 2 },
    { c: "老", py: "lǎo", s: ["lao"], en: "old", rad: "老 old", built: "An old person 耂 with a walking stick 匕", sheet: 2 },
    { c: "师", py: "shī", s: ["shi"], en: "teacher", rad: "巾 cloth", built: "The simple form of 師 — 老师 means teacher", sheet: 2 },
    { c: "名", py: "míng", s: ["ming"], en: "name", rad: "口 mouth", built: "夕 night + 口 mouth — calling someone's name in the dark", sheet: 2 },
    { c: "字", py: "zì", s: ["zi"], en: "character, word", rad: "宀 roof", built: "子 a child under a 宀 roof, writing", sheet: 2 },
    { c: "谁", py: "shéi", s: ["shei", "shui"], en: "who", rad: "讠 speech", built: "讠 speech + 隹 for the sound", sheet: 2 },
    { c: "白", py: "bái", s: ["bai"], en: "white", rad: "白 white", built: "A picture of a bright candle flame", sheet: 2 },
    { c: "红", py: "hóng", s: ["hong"], en: "red", rad: "纟 silk", built: "纟 silk + 工 for the sound", sheet: 2 },
    { c: "黑", py: "hēi", s: ["hei"], en: "black", rad: "黑 black", built: "A face blackened by smoke from 灬 fire", sheet: 2 },

    { c: "可", py: "kě", s: ["ke"], en: "can, may", rad: "口 mouth", built: "口 mouth saying \"yes, you may\"", sheet: 3 },
    { c: "色", py: "sè", s: ["se", "shai"], en: "color", rad: "色 color", built: "A person 人 over 巴", sheet: 3 },
    { c: "点", py: "diǎn", s: ["dian"], en: "dot, o'clock", rad: "灬 fire", built: "灬 fire + 占 for the sound", sheet: 3 },
    { c: "分", py: "fēn", s: ["fen"], en: "divide, minute", rad: "八 eight", built: "八 split apart with 刀 a knife", sheet: 3 },
    { c: "跟", py: "gēn", s: ["gen"], en: "with, follow", rad: "足 foot", built: "足 foot + 艮 for the sound", sheet: 3 },
    { c: "说", py: "shuō", s: ["shuo"], en: "speak, say", rad: "讠 speech", built: "讠 speech + 兑 for the sound", sheet: 3 },
    { c: "喜", py: "xǐ", s: ["xi"], en: "happy, like", rad: "口 mouth", built: "口 mouth + 壴 drum — happy music", sheet: 3 },
    { c: "欢", py: "huān", s: ["huan"], en: "happy, glad", rad: "欠 yawn", built: "又 + 欠 — the simple form of 歡", sheet: 3 },
    { c: "爱", py: "ài", s: ["ai"], en: "love", rad: "爪 claw", built: "爪 hand + 冖 cover + 友 friend", sheet: 3 },
    { c: "叫", py: "jiào", s: ["jiao"], en: "call, be called", rad: "口 mouth", built: "口 mouth + 丩 for the sound", sheet: 3 },

    { c: "去", py: "qù", s: ["qu"], en: "go", rad: "厶 private", built: "A person 土 leaving 厶 a place", sheet: 4 },
    { c: "来", py: "lái", s: ["lai"], en: "come", rad: "木 tree", built: "A picture of a wheat plant", sheet: 4 },
    { c: "现", py: "xiàn", s: ["xian"], en: "now, appear", rad: "王 jade", built: "王 jade + 见 see, for the sound", sheet: 4 },
    { c: "怎", py: "zěn", s: ["zen"], en: "how", rad: "心 heart", built: "心 heart + 乍 for the sound", sheet: 4 },
    { c: "都", py: "dōu", s: ["dou", "du"], en: "all, both", rad: "阝 city", built: "者 for the sound + 阝 city", sheet: 4 },
    { c: "几", py: "jǐ", s: ["ji"], en: "how many", rad: "几 table", built: "A picture of a small table", sheet: 4 },
    { c: "好", py: "hǎo", s: ["hao"], en: "good", rad: "女 woman", built: "女 woman + 子 child", sheet: 4 },
    { c: "了", py: "le", s: ["le", "liao"], en: "(finished)", rad: "亅 hook", built: "A child 子 with no arms", sheet: 4 },
    { c: "吗", py: "ma", s: ["ma"], en: "(question word)", rad: "口 mouth", built: "口 mouth + 马 horse, for the sound", sheet: 4 },
    { c: "是", py: "shì", s: ["shi"], en: "is, am, are; yes", rad: "日 sun", built: "曰 speak + 正 straight — telling it right", sheet: 4 },

    { c: "什", py: "shén", s: ["shen", "shi"], en: "what (什么)", rad: "亻 person", built: "亻 person + 十 ten, for the sound", sheet: 5 },
    { c: "么", py: "me", s: ["me", "ma"], en: "what (什么)", rad: "丿 slash", built: "The simple form of 麼", sheet: 5 },
    { c: "个", py: "gè", s: ["ge"], en: "(counting word)", rad: "丨 line", built: "The simple form of 個", sheet: 5 },
    { c: "岁", py: "suì", s: ["sui"], en: "years old", rad: "山 mountain", built: "山 + 夕 — the simple form of 歲", sheet: 5 },
    { c: "和", py: "hé", s: ["he", "huo", "hu"], en: "and, with", rad: "口 mouth", built: "禾 grain for the sound + 口 mouth", sheet: 5 },
    { c: "多", py: "duō", s: ["duo"], en: "many, a lot", rad: "夕 evening", built: "Two 夕 evenings stacked up — more and more", sheet: 5 },
    { c: "少", py: "shǎo", s: ["shao"], en: "few, a little", rad: "小 small", built: "小 small + 丿 a piece taken away", sheet: 5 },
    { c: "班", py: "bān", s: ["ban"], en: "class", rad: "王 jade", built: "刂 a knife between two pieces of 王 jade", sheet: 5 },
    { c: "谢", py: "xiè", s: ["xie"], en: "thank", rad: "讠 speech", built: "讠 speech + 射 for the sound", sheet: 5 },
    { c: "做", py: "zuò", s: ["zuo"], en: "do, make", rad: "亻 person", built: "亻 person + 故 for the sound", sheet: 5 },

    { c: "以", py: "yǐ", s: ["yi"], en: "use, by (可以)", rad: "人 person", built: "An old picture-character — 可以 means \"can\"", sheet: 6 },
    { c: "在", py: "zài", s: ["zai"], en: "at, in", rad: "土 earth", built: "土 earth + 才 for the sound", sheet: 6 },
    { c: "玩", py: "wán", s: ["wan"], en: "play", rad: "王 jade", built: "王 jade + 元 for the sound — playing with jade", sheet: 6 },
    { c: "级", py: "jí", s: ["ji"], en: "grade, level", rad: "纟 silk", built: "纟 silk + 及 for the sound", sheet: 6 },
    { c: "没", py: "méi", s: ["mei", "mo"], en: "not have", rad: "氵 water", built: "氵 water + 殳 — sinking out of sight", sheet: 6 },
    { c: "有", py: "yǒu", s: ["you"], en: "have", rad: "月 moon", built: "A hand holding 月 (meat) — having something", sheet: 6 },
    { c: "哪", py: "nǎ", s: ["na", "nei"], en: "which, where", rad: "口 mouth", built: "口 mouth + 那 for the sound", sheet: 6 },
    { c: "里", py: "lǐ", s: ["li"], en: "inside", rad: "里 village", built: "田 field + 土 earth", sheet: 6 },
    { c: "也", py: "yě", s: ["ye"], en: "also, too", rad: "乙 second", built: "A picture of a water funnel", sheet: 6 },
    { c: "很", py: "hěn", s: ["hen"], en: "very", rad: "彳 step", built: "彳 step + 艮 for the sound", sheet: 6 },

    { c: "文", py: "wén", s: ["wen"], en: "writing, language", rad: "文 writing", built: "A picture of crossing lines — like writing", sheet: 7 },
    { c: "美", py: "měi", s: ["mei"], en: "pretty; America", rad: "羊 sheep", built: "A person 大 wearing a 羊 ram's-horn headdress", sheet: 7 },
    { c: "国", py: "guó", s: ["guo"], en: "country", rad: "囗 border", built: "玉 jade treasure inside 囗 a border", sheet: 7 },
    { c: "中", py: "zhōng", s: ["zhong"], en: "middle", rad: "丨 line", built: "A line 丨 right through the middle of 口", sheet: 7 },
    { c: "大", py: "dà", s: ["da", "dai"], en: "big", rad: "大 big", built: "A person with arms and legs stretched out wide", sheet: 7 },
    { c: "小", py: "xiǎo", s: ["xiao"], en: "small", rad: "小 small", built: "亅 a line split by 八 — something tiny", sheet: 7 },
    { c: "不", py: "bù", s: ["bu"], en: "not, no", rad: "一 one", built: "A picture of a bird flying away", sheet: 7 },
    { c: "要", py: "yào", s: ["yao"], en: "want", rad: "西 west", built: "覀 hands on the waist of 女 a woman", sheet: 7 },
    { c: "上", py: "shàng", s: ["shang"], en: "up, on", rad: "一 one", built: "A mark above the line 一", sheet: 7 },
    { c: "过", py: "guò", s: ["guo"], en: "pass, cross", rad: "辶 walk", built: "辶 walk + 寸 — the simple form of 過", sheet: 7 },

    { c: "的", py: "de", s: ["de", "di"], en: "of, 's", rad: "白 white", built: "白 white + 勺 for the sound", sheet: 8 },
    { c: "学", py: "xué", s: ["xue"], en: "learn, study", rad: "子 child", built: "子 a child studying under a roof", sheet: 8 },
    { c: "生", py: "shēng", s: ["sheng"], en: "be born, grow", rad: "生 life", built: "A plant sprouting up from 土 the earth", sheet: 8 },
    { c: "们", py: "men", s: ["men"], en: "(more than one)", rad: "亻 person", built: "亻 person + 门 door, for the sound", sheet: 8 },
    { c: "号", py: "hào", s: ["hao"], en: "number, date", rad: "口 mouth", built: "口 mouth + 丂 — the simple form of 號", sheet: 8 },
    { c: "年", py: "nián", s: ["nian"], en: "year", rad: "干 dry", built: "A person carrying 禾 grain at harvest, once a year", sheet: 8 },
    { c: "今", py: "jīn", s: ["jin"], en: "today, now", rad: "人 person", built: "A mouth talking about things happening now", sheet: 8 },
    { c: "明", py: "míng", s: ["ming"], en: "bright; next", rad: "日 sun", built: "日 sun + 月 moon — very bright", sheet: 8 },
    { c: "后", py: "hòu", s: ["hou"], en: "after, behind", rad: "口 mouth", built: "A person bending forward to orders from 口 a mouth", sheet: 8 },
    { c: "昨", py: "zuó", s: ["zuo"], en: "yesterday", rad: "日 sun", built: "日 day + 乍 for the sound", sheet: 8 },

    { c: "前", py: "qián", s: ["qian"], en: "front, before", rad: "刂 knife", built: "Feet on a boat with oars, moving forward", sheet: 9 },
    { c: "天", py: "tiān", s: ["tian"], en: "sky, day", rad: "大 big", built: "一 the sky above 大 a person", sheet: 9 },
    { c: "日", py: "rì", s: ["ri"], en: "sun, day", rad: "日 sun", built: "A picture of the sun", sheet: 9 },
    { c: "月", py: "yuè", s: ["yue"], en: "moon, month", rad: "月 moon", built: "A picture of a half moon", sheet: 9 },
    { c: "星", py: "xīng", s: ["xing"], en: "star", rad: "日 sun", built: "日 + 生 for the sound", sheet: 9 },
    { c: "期", py: "qī", s: ["qi", "ji"], en: "period of time (星期 = week)", rad: "月 moon", built: "月 month + 其 for the sound", sheet: 9 },
    { c: "六", py: "liù", s: ["liu"], en: "six", rad: "八 eight", built: "Borrowed for its sound", sheet: 9 },
    { c: "七", py: "qī", s: ["qi"], en: "seven", rad: "一 one", built: "Like 十 with a bent stroke", sheet: 9 },
    { c: "九", py: "jiǔ", s: ["jiu"], en: "nine", rad: "乙 second", built: "A picture of a bent elbow", sheet: 9 },
    { c: "八", py: "bā", s: ["ba"], en: "eight", rad: "八 eight", built: "Two strokes splitting apart", sheet: 9 }
  ]
};

/* Common characters for each toneless syllable. The speech recognizer writes
   characters, not sounds, so a correct "tā" may come back as 他, 她 or 它 —
   all of them count. */
window.MANDARIN_HOMOPHONES = {
  ni: "你泥尼呢拟逆腻妮倪匿溺", wo: "我窝握卧沃喔蜗", ta: "他她它塔踏塌",
  jie: "姐接街节结解介界借届阶揭洁戒杰捷皆", mei: "妹没美每梅媒煤眉霉枚魅玫",
  ge: "哥个歌各格鸽割搁隔革阁葛戈", di: "弟地第低底帝递敌滴迪笛抵的",
  jia: "家加假价架嫁夹甲佳驾", ren: "人认任仁忍刃韧", peng: "朋碰捧鹏棚蓬膨彭烹",
  you: "友有又右由油游优幼尤邮犹悠", lao: "老劳牢捞姥佬", ming: "名明命鸣铭",
  shi: "师是十时事使世市试石识实史始室式视示湿诗施失狮尸士氏什",
  zi: "字子自紫资姿仔滋籽", shei: "谁", shui: "水睡税谁", bai: "白百拜摆败柏",
  hong: "红洪虹宏轰哄鸿", hei: "黑嘿", ke: "可课客科克刻渴棵颗壳咳",
  se: "色瑟涩塞", shai: "晒筛色", dian: "点电店典垫殿淀颠", fen: "分份粉纷奋愤坟芬",
  gen: "跟根", shuo: "说硕烁朔", xi: "喜西洗系习细戏吸希息席稀溪惜熙膝锡",
  huan: "欢换还环缓患幻唤", ai: "爱哎矮碍挨癌艾唉", jiao: "叫教脚交角觉较焦胶浇骄郊",
  qu: "去取区曲趣渠娶", lai: "来赖莱", xian: "现先线县限显鲜险献闲咸仙贤", zen: "怎",
  dou: "都斗豆抖逗兜陡", du: "都度读独毒肚堵杜渡赌",
  ji: "几机鸡记己级急计及极集纪技寄季际挤即积基激吉期", hao: "好号毫豪耗浩",
  le: "了乐勒", liao: "了料聊疗辽", ma: "吗妈马骂麻嘛码蚂么", me: "么",
  shen: "什身深神甚伸肾审", sui: "岁随碎虽穗", he: "和喝河合何盒荷核贺",
  huo: "和活火或货获伙", hu: "和湖胡虎户护糊壶呼", duo: "多朵躲夺舵",
  shao: "少烧勺稍哨绍", ban: "班半办板般搬伴扮版拌", xie: "谢写些鞋血协斜歇携",
  zuo: "做作坐左座昨佐", yi: "以一已乙意衣医易亿义艺议依移遗疑椅",
  zai: "在再载灾栽", wan: "玩完晚万碗湾弯丸挽", mo: "没摸磨末莫默墨魔抹",
  na: "哪那拿纳", nei: "哪内", li: "里理力立利礼李离历例丽厘梨粒",
  ye: "也夜叶业野爷页液耶", hen: "很恨狠痕", wen: "文问闻温稳吻纹蚊",
  guo: "国过果锅郭裹", zhong: "中种重钟终众忠肿", da: "大打答达搭", dai: "大带代待袋戴呆",
  xiao: "小笑校效孝晓萧肖销消", bu: "不步部布补捕", yao: "要药咬摇腰遥邀耀",
  shang: "上商伤赏尚裳", de: "的得德地", xue: "学雪血穴靴",
  sheng: "生声省升胜圣绳盛剩", men: "们门闷", nian: "年念粘碾",
  jin: "今进近金斤紧仅禁尽劲津", hou: "后候厚猴喉吼",
  qian: "前钱千签浅欠牵铅迁", tian: "天田甜填添", ri: "日", yue: "月越乐约阅跃悦",
  xing: "星行兴形性姓幸醒型", qi: "期七起其气汽奇骑旗企棋妻器",
  liu: "六流留刘柳溜", jiu: "九就旧酒久救究舅", ba: "八把爸吧拔巴坝"
};
